# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: IT's Notes

description: Stylish Jekyll Theme
author:
  name: anhlt
  email: anhlt.bka@gmail.com
  github: 111rC0d3r
  twitter: MrCoder6
  pinterest: asd123
  linkedin: anhlt
  description: IT's Notes
  bio: Thế giới quả là rộng lớn, và có rất nhiều việc phải làm!
  email_md5: 93200d22e24d30e758e0bc5e37ae335d

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
